<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Club de Veleros de San Isidro</title>
<link rel="stylesheet" type="text/css" href="view.css" media="all">
<script type="text/javascript" src="view.js"></script>

</head>
<body id="main_body" >
	<img id="top" src="top.png" alt="">
	<div id="form_container">
		<h1><a>Club de Veleros de San Isidro</a></h1>
		<form id="form_634721" class="appnitro"  method="post" action="rconsua.php">
    		<div class="form_description">
                <h2>Club de Veleros de San Isidro</h2>
                <p>Ingrese parte del Nombre a consultar</p>
    		</div>

	   		<ul >
    			<li id="li_2" >
	               	<label class="description" for="element_2">Parte del nombre del Socio </label>

                        <div>
        	       		  <input id="cSocio" name="cSocio" class="element text large" type="text" maxlength="255" value=""/>
                        </div>
                </li>
			
				<li class="buttons">
                    <input type="hidden" name="form_id" value="634721" />
                    <input id="saveForm" class="button_text" type="submit" name="submit" value="consultar" />
        		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">terco 2009</a>
		</div>
	</div>
	<img id="bottom" src="bottom.png" alt="">
	</body>
</html>
